//
// File generated by rootcint at Wed Aug  8 13:57:46 2012

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME rootdict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "rootdict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void Gui_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_Gui(void *p = 0);
   static void *newArray_Gui(Long_t size, void *p);
   static void delete_Gui(void *p);
   static void deleteArray_Gui(void *p);
   static void destruct_Gui(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::Gui*)
   {
      ::Gui *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::Gui >(0);
      static ::ROOT::TGenericClassInfo 
         instance("Gui", ::Gui::Class_Version(), "./gui.h", 17,
                  typeid(::Gui), DefineBehavior(ptr, ptr),
                  &::Gui::Dictionary, isa_proxy, 4,
                  sizeof(::Gui) );
      instance.SetNew(&new_Gui);
      instance.SetNewArray(&newArray_Gui);
      instance.SetDelete(&delete_Gui);
      instance.SetDeleteArray(&deleteArray_Gui);
      instance.SetDestructor(&destruct_Gui);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::Gui*)
   {
      return GenerateInitInstanceLocal((::Gui*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Gui*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *Gui::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *Gui::Class_Name()
{
   return "Gui";
}

//______________________________________________________________________________
const char *Gui::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Gui*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int Gui::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Gui*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void Gui::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Gui*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *Gui::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Gui*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void Gui::Streamer(TBuffer &R__b)
{
   // Stream an object of class Gui.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(Gui::Class(),this);
   } else {
      R__b.WriteClassBuffer(Gui::Class(),this);
   }
}

//______________________________________________________________________________
void Gui::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class Gui.
      TClass *R__cl = ::Gui::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_timer", &_timer);
      R__insp.InspectMember(_timer, "_timer.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_canvas", &_canvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_channel", &_channel);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_port", &_port);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_width", &_width);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_offset", &_offset);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_host", &_host);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_status", &_status);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_subtractTrigger", &_subtractTrigger);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_runningAverage", &_runningAverage);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_firstHit", &_firstHit);
      TGMainFrame::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_Gui(void *p) {
      return  p ? new(p) ::Gui : new ::Gui;
   }
   static void *newArray_Gui(Long_t nElements, void *p) {
      return p ? new(p) ::Gui[nElements] : new ::Gui[nElements];
   }
   // Wrapper around operator delete
   static void delete_Gui(void *p) {
      delete ((::Gui*)p);
   }
   static void deleteArray_Gui(void *p) {
      delete [] ((::Gui*)p);
   }
   static void destruct_Gui(void *p) {
      typedef ::Gui current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::Gui

/********************************************************
* rootdict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablerootdict();

extern "C" void G__set_cpp_environmentrootdict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("gui.h");
  G__cpp_reset_tagtablerootdict();
}
#include <new>
extern "C" int G__cpp_dllrevrootdict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Gui */
static int G__rootdict_309_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Gui*) G__getstructoffset())->OnTimer();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_309_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Gui*) G__getstructoffset())->ProcessSettings();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_309_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Gui* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Gui[n];
     } else {
       p = new((void*) gvp) Gui[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Gui;
     } else {
       p = new((void*) gvp) Gui;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__rootdictLN_Gui));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_309_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) Gui::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_309_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Gui::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_309_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) Gui::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_309_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      Gui::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_309_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Gui*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_309_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Gui::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_309_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Gui::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_309_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Gui::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_309_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Gui::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Gui G__TGui;
static int G__rootdict_309_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Gui*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Gui*) (soff+(sizeof(Gui)*i)))->~G__TGui();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Gui*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Gui*) (soff))->~G__TGui();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Gui */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncrootdict {
 public:
  G__Sizep2memfuncrootdict(): p(&G__Sizep2memfuncrootdict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncrootdict::*p)();
};

size_t G__get_sizep2memfuncrootdict()
{
  G__Sizep2memfuncrootdict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancerootdict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__rootdictLN_Gui))) {
     Gui *G__Lderived;
     G__Lderived=(Gui*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rootdictLN_Gui),G__get_linked_tagnum(&G__rootdictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rootdictLN_Gui),G__get_linked_tagnum(&G__rootdictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rootdictLN_Gui),G__get_linked_tagnum(&G__rootdictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rootdictLN_Gui),G__get_linked_tagnum(&G__rootdictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rootdictLN_Gui),G__get_linked_tagnum(&G__rootdictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rootdictLN_Gui),G__get_linked_tagnum(&G__rootdictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rootdictLN_Gui),G__get_linked_tagnum(&G__rootdictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablerootdict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Gui */
static void G__setup_memvarGui(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__rootdictLN_Gui));
   { Gui *p; p=(Gui*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__rootdictLN_TTimer),-1,-1,4,"_timer=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TCanvas),-1,-1,4,"_canvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGNumberEntry),-1,-1,4,"_channel=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGNumberEntry),-1,-1,4,"_port=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGNumberEntry),-1,-1,4,"_width=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGNumberEntry),-1,-1,4,"_offset=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGTextEntry),-1,-1,4,"_host=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGStatusBar),-1,-1,4,"_status=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGCheckButton),-1,-1,4,"_subtractTrigger=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGCheckButton),-1,-1,4,"_runningAverage=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGCheckButton),-1,-1,4,"_firstHit=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarrootdict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncGui(void) {
   /* Gui */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__rootdictLN_Gui));
   G__memfunc_setup("init",436,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HandleKey",885,(G__InterfaceMethod) NULL, 103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 4, 0, "U 'Event_t' - 0 - event", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("OnTimer",702,G__rootdict_309_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ProcessSettings",1584,G__rootdict_309_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Gui",293,G__rootdict_309_0_5, 105, G__get_linked_tagnum(&G__rootdictLN_Gui), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__rootdict_309_0_6, 85, G__get_linked_tagnum(&G__rootdictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&Gui::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__rootdict_309_0_7, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Gui::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__rootdict_309_0_8, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&Gui::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__rootdict_309_0_9, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&Gui::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__rootdictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__rootdict_309_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__rootdict_309_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Gui::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__rootdict_309_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Gui::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__rootdict_309_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Gui::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__rootdict_309_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Gui::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~Gui", 419, G__rootdict_309_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncrootdict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalrootdict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcrootdict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__rootdictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TTimer = { "TTimer" , 99 , -1 };
G__linked_taginfo G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rootdictLN_Event_t = { "Event_t" , 115 , -1 };
G__linked_taginfo G__rootdictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__rootdictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TGNumberEntry = { "TGNumberEntry" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TGTextEntry = { "TGTextEntry" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TGStatusBar = { "TGStatusBar" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TGCheckButton = { "TGCheckButton" , 99 , -1 };
G__linked_taginfo G__rootdictLN_Gui = { "Gui" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablerootdict() {
  G__rootdictLN_TClass.tagnum = -1 ;
  G__rootdictLN_TBuffer.tagnum = -1 ;
  G__rootdictLN_TMemberInspector.tagnum = -1 ;
  G__rootdictLN_TObject.tagnum = -1 ;
  G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rootdictLN_TTimer.tagnum = -1 ;
  G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rootdictLN_Event_t.tagnum = -1 ;
  G__rootdictLN_TGObject.tagnum = -1 ;
  G__rootdictLN_TQObject.tagnum = -1 ;
  G__rootdictLN_TGWindow.tagnum = -1 ;
  G__rootdictLN_TGFrame.tagnum = -1 ;
  G__rootdictLN_TGCompositeFrame.tagnum = -1 ;
  G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__rootdictLN_TGMainFrame.tagnum = -1 ;
  G__rootdictLN_TCanvas.tagnum = -1 ;
  G__rootdictLN_TGNumberEntry.tagnum = -1 ;
  G__rootdictLN_TGTextEntry.tagnum = -1 ;
  G__rootdictLN_TGStatusBar.tagnum = -1 ;
  G__rootdictLN_TGCheckButton.tagnum = -1 ;
  G__rootdictLN_Gui.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablerootdict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__rootdictLN_TClass);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TObject);
   G__get_linked_tagnum_fwd(&G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TTimer);
   G__get_linked_tagnum_fwd(&G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__rootdictLN_Event_t);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TCanvas);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TGNumberEntry);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TGTextEntry);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TGStatusBar);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TGCheckButton);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__rootdictLN_Gui),sizeof(Gui),-1,323840,(char*)NULL,G__setup_memvarGui,G__setup_memfuncGui);
}
extern "C" void G__cpp_setuprootdict(void) {
  G__check_setup_version(30051515,"G__cpp_setuprootdict()");
  G__set_cpp_environmentrootdict();
  G__cpp_setup_tagtablerootdict();

  G__cpp_setup_inheritancerootdict();

  G__cpp_setup_typetablerootdict();

  G__cpp_setup_memvarrootdict();

  G__cpp_setup_memfuncrootdict();
  G__cpp_setup_globalrootdict();
  G__cpp_setup_funcrootdict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncrootdict();
  return;
}
class G__cpp_setup_initrootdict {
  public:
    G__cpp_setup_initrootdict() { G__add_setup_func("rootdict",(G__incsetup)(&G__cpp_setuprootdict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initrootdict() { G__remove_setup_func("rootdict"); }
};
G__cpp_setup_initrootdict G__cpp_setup_initializerrootdict;

